### ISSUE TITLE
Update PHP formulaes to include SOAP

### ISSUE THREAD

**Issue by diazwatson** [henkrehorst/homebrew-php#11]
When testing and debugging systems that use PHP SOAP we need to use alternative methods like install a vagrant box because the PHP versions in valet do not have it out of the box.

How difficult would be to do this?

I will be happy to help creating a PR if somebody assist me with guidance on making such change.

**Comment by Neodork** [comment]
@diazwatson Checked all the formulae. The formulae all have `--enable-soap`. Meaning SOAP is enabled by default. I work with valet-php@7.0 and @7.2 on a daily basis using the SOAP extension.

Do you have valet-php installed or php (the on from original brew tap)?
Could you elaborate your reason for wanting to disable the soap functionality?

**Comment by diazwatson** [comment]
Hi @Neodork 
You are right!, I have just re checked this in all valet-php versions I have installed and it is indeed  enabled.

![Screenshot 2019-07-30 at 11 12 56](https://user-images.githubusercontent.com/1080386/62121192-08eeb180-b2bb-11e9-9469-206df26d8623.png)

Don't know why I didn't see this when debugging a SOAP issue the other day 🤦‍♂ 

Thanks for clarifying 👍

**Comment by Neodork** [comment]
My pleasure enjoy programming using valet+!

**Comment by diazwatson** [comment]
I do enjoy, I flipling love it 😍 🙌
