### ISSUE TITLE
Cannot install php 8.0 with Mac Big Sur

### ISSUE THREAD

**Issue by jcuerdo** [henkrehorst/homebrew-php#110]
➜  ~ brew install valet-php@8.0
==> Installing valet-php@8.0 from henkrehorst/php
==> Downloading https://dl.bintray.com/henkrehorst/valet-php/valet-php%408.0-8.0
#=#=#
curl: (22) The requested URL returned error: 404 Not Found
Error: Failed to download resource "valet-php@8.0"
Download failed: https://dl.bintray.com/henkrehorst/valet-php/valet-php%408.0-8.0.0.catalina.bottle.tar.gz
Warning: Bottle installation failed: building from source.
==> Downloading https://www.php.net/distributions/php-8.0.0.tar.xz
Already downloaded: /Users/USER/Library/Caches/Homebrew/downloads/931327716c2fdbb4db0a09a404f5d0d208381bfa0ed2064764652a4f8578b4ef--php-8.0.0.tar.xz
==> Patching
==> ./buildconf --force
==> ./configure --prefix=/usr/local/Cellar/valet-php@8.0/8.0.0 --localstatedir=/
==> make
==> make install
Last 15 lines from /Users/USER/Library/Logs/Homebrew/valet-php@8.0/04.make:
make: *** [install-sapi] Error 1
make: *** Waiting for unfinished jobs....
mkdir: /usr/local/Cellar/valet-php@8.0/8.0.0/share: File exists
mkdir: /usr/local/Cellar/valet-php@8.0/8.0.0/share/man: File exists
mkdir: /usr/local/Cellar/valet-php@8.0/8.0.0/share/man/man1: File exists
  program: phpize
Installing phpdbg man page:       /usr/local/Cellar/valet-php@8.0/8.0.0/share/man/man1/
Installing PHP FPM defconfig:     /usr/local/etc/valet-php/8.0/
  program: php-config
Installing man pages:             /usr/local/Cellar/valet-php@8.0/8.0.0/share/man/man1/
  page: phpize.1
Installing PHP FPM man page:      /usr/local/Cellar/valet-php@8.0/8.0.0/share/man/man8/
  page: php-config.1
Installing PHP FPM status page:   /usr/local/Cellar/valet-php@8.0/8.0.0/share/php/fpm/
Installing header files:          /usr/local/Cellar/valet-php@8.0/8.0.0/include/php/

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/henkrehorst/homebrew-php/issues

**Comment by svera** [comment]
@jcuerdo is not related with Big Sur, as I'm having the same issue with Catalina with XCode version 12.2

**Comment by henkrehorst** [comment]
Fixed with the latest release
