### ISSUE TITLE
Big sur support

### ISSUE THREAD

**Issue by henkrehorst** [henkrehorst/homebrew-php#113]
Valet-php will provide compiled support for macos big sur early 2021. You can follow here the process of big sur support.

**Comment by convenient** [comment]
This was the point big sur was bottled in the homebrew core https://github.com/Homebrew/homebrew-core/blame/50b508566111337f8f576d5d43a530e3938fe934/Formula/php.rb

Might be a good starting point.

**Comment by henkrehorst** [comment]
Fixed with the latest release
