### ISSUE TITLE
Please update valet-php@7.2 to latest version

### ISSUE THREAD

**Issue by danherd** [henkrehorst/homebrew-php#12]
There is an annoying Symfony/PHP bug that has been squashed in 7.2.21

See: https://github.com/symfony/symfony/issues/32395

Thanks!

**Comment by henkrehorst** [comment]
Hey @danherd,

I just updated all the php versions to the latest version.  In your case get the latest php 7.2 by run `brew upgrade valet-php@7.2` and run `valet restart`.

**Comment by danherd** [comment]
Thank you!
