### ISSUE TITLE
PHP 5.6 cannot build from source

### ISSUE THREAD

**Issue by convenient** [henkrehorst/homebrew-php#13]
I think this only works because it's been bottled.

See https://travis-ci.com/convenient/henkrehorst-homebrew-php-tests/builds/127353923 for logs

See https://github.com/convenient/henkrehorst-homebrew-php-tests/blob/master/.travis.yml#L12 for the test setup

**Comment by henkrehorst** [comment]
Hi @convenient ,

Sorry for my late response. I solved yesterday the compiling issue of php 5.6. 

Thanks for your support
