### ISSUE TITLE
dyld: Library not loaded

### ISSUE THREAD

**Issue by dude2511** [henkrehorst/homebrew-php#137]
Latest upgrades lead to the following problem: 

(base) ➜  bin php
dyld: Library not loaded: /usr/local/opt/icu4c/lib/libicuio.67.dylib
  Referenced from: /usr/local/bin/php
  Reason: image not found
[1]    3583 abort      php

tested with linked valet-php 7.2

I looked at the installed icu4c version and found icu4c 68.2. Should I downgrade icu4c?

**Comment by itsbreadd** [comment]
Also having this issue.

Have tried downgrading icu4c which allows me to use 7.2 but then switching to 7.4 results in the icu4c version being incompatible.

Not sure if you're flexible on which php version you use but if you run
brew install --build-from-source valet-php@7.4

You should be able to use 7.4 without issue

**Comment by dude2511** [comment]
Thank you for your advice, I will try it later at home.

There is just one application that is tested for 7.2 only. So hopefully there will be a fix soon.

**Comment by henkrehorst** [comment]
Thanks for your issue, all problems should now be fixed
