### ISSUE TITLE
Compatibility with brew 3.1.0 

### ISSUE THREAD

**Issue by malikahmed1996** [henkrehorst/homebrew-php#146]
The latest version of HomeBrew (3.1.0) lead to the following problems: 

<img width="1280" alt="Screen Shot 2021-04-12 at 3 51 28 PM" src="https://user-images.githubusercontent.com/32421711/114384541-463ac600-9ba8-11eb-9017-d8df4b7ed3a3.png">

**Comment by malikahmed1996** [comment]
To fix the above issue I ran the command brew style --fix {FORMULA}. it fixed the issue for me and I created a PR for the fixed version issue.

**Comment by henkrehorst** [comment]
He @malikahmed1996,

Thanks for your issue and pr. I merged your pr🙂
