### ISSUE TITLE
PHP 7.3 and 7.4 are missing "keg_only :versioned_formula"

### ISSUE THREAD

**Issue by Neodork** [henkrehorst/homebrew-php#15]
Het there!

We're noticing some issues in valet-plus caused by some formulae not being set as KEG ONLY.

Please add 

`keg_only :versioned_formula`

to: 
- https://github.com/henkrehorst/homebrew-php/blob/master/Formula/valet-php%407.3.rb
- https://github.com/henkrehorst/homebrew-php/blob/master/Formula/valet-php%407.4.rb

Like the other formulae (5.6, 7.0 7.1, 7.2). Seems like only 7.3 and 7.4 are missing these.

Kind regards,
Neodork

**Comment by henkrehorst** [comment]
He @Neodork ,

I added the KEG ONLY in valet-php 7.3 and 7.4. I also rebuilt the binaries for valet php 7.3 and 7.4
