### ISSUE TITLE
Error: Failed to download resource "valet-php@7.2"

### ISSUE THREAD

**Issue by elburro1887** [henkrehorst/homebrew-php#157]
```
brew reinstall valet-php@7.2


==> Downloading https://dl.bintray.com/henkrehorst/valet-php/valet-php%407.2-7.2.34_4.sierra.bottle.tar.gz

curl: (35) LibreSSL SSL_connect: SSL_ERROR_SYSCALL in connection to dl.bintray.com:443
Error: Failed to download resource "valet-php@7.2"
Download failed: https://dl.bintray.com/henkrehorst/valet-php/valet-php%407.2-7.2.34_4.sierra.bottle.tar.gz
```

If you open the URL in the browser, you also get an error. So I assume the host is down or misconfigured?

https://dl.bintray.com/henkrehorst/valet-php/valet-php%407.2-7.2.34_4.sierra.bottle.tar.gz

**Comment by Davie82** [comment]
Hi @elburro1887,

See https://github.com/henkrehorst/homebrew-php/issues/148 for more information. I think this is the same issue.

**Comment by elburro1887** [comment]
@Davie82 Thanks, yes.
I will close this issue.
