### ISSUE TITLE
Upgrade valet-php@7.3 to latest release

### ISSUE THREAD

**Issue by code2prog** [henkrehorst/homebrew-php#3]
in php 7.3.0 there is an error that causes the queue to malfunction. Bug was fixed in php 7.3.1
https://github.com/laravel/framework/issues/26819

Please update php 7.3 to the last stable release

Thanks

**Comment by henkrehorst** [comment]
Thanks code2prog for your issue,

I have now updated the php 7.3.0 to php 7.3.1. Run `brew upgrade valet-php@7.3` and run `valet restart`. Now valet-php@7.3 has been updated to php 7.3.1 on your mac. Shortly all php versions in this brew tap will be updated automatically by an app that I'm currently working on.
