### ISSUE TITLE
After Installing, Valet still doesn't recognize php version.

### ISSUE THREAD

**Issue by christian-walker** [henkrehorst/homebrew-php#4]
After tapping henkrehorst/homebrew-php it installs all php versions (5.6,7.0,7.1,7.2,7.3).  However, it installs them as valet-php@ in`usr/local/Cellar` https://www.screencast.com/t/S2JxU0PL
If you try to run `valet use 5.6` it will look for php@5.6 directory in usr/local/Cellar and not valet-php@5.6.

**Solution/Hack:**
To fix this I duplicated thd valet-php directories and renamed them, removing the valet- prefix.

Is there a place I can go to change this to look for the new directory name instead of duplicating the ones that were created?

**Comment by Neodork** [comment]
@christian-walker What version is your valet currently on? What does `valet on-latest-version` return to you? Could you add your version? I am pretty sure I PR-ed the change to the formulae names.

**Comment by christian-walker** [comment]
@Neodork it returned NO.  I went ahead and updated valet to the latest version and it using the new setup now. Thanks!
