### ISSUE TITLE
How to upgrade php?

### ISSUE THREAD

**Issue by vincent2090311** [henkrehorst/homebrew-php#6]
Im using valet+ v1.0.26 and i want to upgrade to php 7.1.26 (you release packet last month). But I dont know how. Could you show me how?

**Comment by alexblueacorn** [comment]
do:
valet use 7.1

and it supposed to install it and switch to it

**Comment by vincent2090311** [comment]
@alexblueacorn 
I already running php 7.1 but its older than 7.1.26. So when I use command above, it will not install new version

**Comment by alexblueacorn** [comment]
Right now for me it installs 7.1.25

**Comment by henkrehorst** [comment]
Hi @vincent2090311 & @alexblueacorn ,

@vincent2090311 you are right the valet-php@7.1 runs 1 version behind. I'm busy automating the brew tap. I hope the app for automatic update of the php version, is live on Sunday Night (dutch time) and then all php versions update in brew tap to the most recent versions.

**Comment by vincent2090311** [comment]
@henkrehorst 
Any news on this?

**Comment by Neodork** [comment]
@vincent2090311 @alexblueacorn Are you guys still having issues with the version mismatch? If so I can ask @henkrehorst to do a manual build while he works on the automation.

**Comment by henkrehorst** [comment]
@vincent2090311 @alexblueacorn @Neodork I updated all php versions last Friday, all php versions must be correct after a brew update & brew upgrade.

**Comment by Neodork** [comment]
Great! Closing this one.
