### ISSUE TITLE
valet-php@7.3 does not install properly. 

### ISSUE THREAD

**Issue by alexblueacorn** [henkrehorst/homebrew-php#7]
PHP Warning:  Module 'apcu' already loaded in Unknown on line 0
PHP Warning:  Module 'apcu' already loaded in Unknown on line 0
PHP Warning:  Module 'apc' already loaded in Unknown on line 0
PHP Warning:  Module 'apcu' already loaded in Unknown on line 0
PHP Warning:  Module 'apcu' already loaded in Unknown on line 0
PHP Warning:  Module 'apcu' already loaded in Unknown on line 0
PHP Warning:  Module 'apc' already loaded in Unknown on line 0
PHP Warning:  Module 'apcu' already loaded in Unknown on line 0
PHP Parse error:  syntax error, unexpected 'apcu' (T_STRING), expecting ')' in Command line code on line 2
PHP Warning:  Module 'apcu' already loaded in Unknown on line 0
PHP Warning:  Module 'apcu' already loaded in Unknown on line 0
PHP Warning:  Module 'apc' already loaded in Unknown on line 0
PHP Warning:  Module 'apcu' already loaded in Unknown on line 0
PHP Warning:  Module 'apcu' already loaded in Unknown on line 0
PHP Warning:  Module 'apcu' already loaded in Unknown on line 0
PHP Warning:  Module 'apc' already loaded in Unknown on line 0
PHP Warning:  Module 'apcu' already loaded in Unknown on line 0
PHP Parse error:  syntax error, unexpected 'apcu' (T_STRING), expecting ')' in Command line code on line 2
PHP Warning:  Module 'apcu' already loaded in Unknown on line 0

Warning: Module 'apcu' already loaded in Unknown on line 0
PHP Warning:  Module 'apcu' already loaded in Unknown on line 0

Warning: Module 'apcu' already loaded in Unknown on line 0
PHP Warning:  Module 'apc' already loaded in Unknown on line 0

Warning: Module 'apc' already loaded in Unknown on line 0
PHP Warning:  Module 'apcu' already loaded in Unknown on line 0

Warning: Module 'apcu' already loaded in Unknown on line 0
Could not open input file: 
Warning: Module 'apcu' already loaded in Unknown on line 0

Warning: Module 'apcu' already loaded in Unknown on line 0

Warning: Module 'apc' already loaded in Unknown on line 0

Warning: Module 'apcu' already loaded in Unknown on line 0

Parse error: syntax error, unexpected 'apcu' (T_STRING), expecting ')' in Command line code on line 2/cli/valet.php

**Comment by henkrehorst** [comment]
Hi Alex,

This probably has to do with the fact that this php version, 1 version behind is of the most recent version. Sunday evening (Dutch time) then I hope to finish the app for the automatic updating of the homebrew-php tap. With this app all php versions will always be up to date in this tap.

**Comment by henkrehorst** [comment]
Hi @alexblueacorn ,

This is a valet plus issue, if you run a valet fix, the php ini will be reset and the issue will be resolved.
