### ISSUE TITLE
Brew update broke php - libicui18n.66.dylib library requested 

### ISSUE THREAD

**Issue by dingo-d** [henkrehorst/homebrew-php#72]
I did a brew update and that updated the icu4u lib to version 67.1 (which seems to be the latest one according to the commit at the [homebrew-core](https://github.com/Homebrew/homebrew-core/commits/master?after=a8b65a4e9bb7f3c7a35ceef34af200668cec46c2+174)), and it looks like the `valet-php@7.3` looks for the version 66.

I tried uninstalling and reinstalling the `valet-php@7.3` but no luck. I still get

```bash
dyld: Library not loaded: /usr/local/opt/icu4c/lib/libicui18n.66.dylib
  Referenced from: /usr/local/opt/valet-php@7.3/bin/php
  Reason: image not found
[1]    11497 abort      php -v
```

Any idea how to fix this, other than trying to branch the old commit of the v66 of the icu4u lib and checking that out temporarily?

**Comment by henkrehorst** [comment]
Hi,

The problem is with the valet-php bottles, i rebuilding them now within 3 hours all the php versions are working again.

**Comment by dingo-d** [comment]
Yup, seems to be working now. I've reinstalled the icu4c to the latest version, removed old and reinstalled new version. Thanks!

**Comment by mpg756** [comment]
Hi, henkrehorst, have faced same issue with libicui18n.66.dylib on valet-php@7.2 and valet-php@7.1. Could you please update them also?

**Comment by viktorbijlenga** [comment]
@mpg756 It's updated now. Henk needed to rebuild the valet-php bottles, which took some time. Should be working now again.
