### ISSUE TITLE
valet-php@5.6 does not install with icu4c v.: 64.2

### ISSUE THREAD

**Issue by dostrog** [henkrehorst/homebrew-php#8]
valet-php@5.6 does not install if using icu4c v.:64.2. With icu4c v.:63.* it does.

```
$ brew info icu4c
icu4c: stable 64.2 (bottled) [keg-only]
...

```
```
$brew install valet-php@5.6
==> Installing valet-php@5.6 from henkrehorst/php
==> Downloading https://dl.bintray.com/henkrehorst/homebrew-php/valet-php@5.6-5.6.39.mojave.bottle.tar.gz
Already downloaded: /Users/sergey/Library/Caches/Homebrew/downloads/afcf60b4c1cd1b239c755b9e41b2378ce52817097625eca4ff6386b467b0a1c6--valet-php@5.6-5.6.39.mojave.bottle.tar.gz
==> Pouring valet-php@5.6-5.6.39.mojave.bottle.tar.gz
==> /usr/local/Cellar/valet-php@5.6/5.6.39/bin/pear config-set php_ini /usr/local/etc/valet-php/5.6/php.ini system
Last 15 lines from /Users/sergey/Library/Logs/Homebrew/valet-php@5.6/post_install.01.pear:
2019-04-19 13:11:17 +0200

/usr/local/Cellar/valet-php@5.6/5.6.39/bin/pear
config-set
php_ini
/usr/local/etc/valet-php/5.6/php.ini
system

dyld: Library not loaded: /usr/local/opt/icu4c/lib/libicui18n.63.dylib
  Referenced from: /usr/local/Cellar/valet-php@5.6/5.6.39/bin/php
  Reason: image not found
…

```

**Comment by jordykommeren** [comment]
I've been experiencing the same issue. Currently it's impossible to install valet and get it to work. After hours of crawling all over the internet good old stackoverflow helped me to get it fixed!

**Here's how I did it:**
1. We first need a deep clone of the Homebrew repo. This may take a while: git -C $(brew --repo homebrew/core) fetch --unshallow
2. brew log icu4c to track down a commit that references 63.X; bc0c97952453ff6afc146aa3a706e9902aba4300 does the trick.
3. cd $(brew --repo homebrew/core)
4. git checkout bc0c97952453ff6afc146aa3a706e9902aba4300 -- Formula/icu4c.rb
5. brew uninstall  --ignore-dependencies icu4c
6. brew install icu4c You should now have the correct version of the dependency! Now just to...
7. git reset && git checkout . Cleanup your modified recipe.
8. I had to do a brew switch icu4c 63.1 to make it all work again.

See https://stackoverflow.com/a/54273234 for additional information.
This seems the only way to fix it right now.

**Comment by jordykommeren** [comment]
> valet-php@5.6 does not install if using icu4c v.:64.2. With icu4c v.:63.* it does.
> 
> ```
> $ brew info icu4c
> icu4c: stable 64.2 (bottled) [keg-only]
> ...
> ```
> ```
> $brew install valet-php@5.6
> ==> Installing valet-php@5.6 from henkrehorst/php
> ==> Downloading https://dl.bintray.com/henkrehorst/homebrew-php/valet-php@5.6-5.6.39.mojave.bottle.tar.gz
> Already downloaded: /Users/sergey/Library/Caches/Homebrew/downloads/afcf60b4c1cd1b239c755b9e41b2378ce52817097625eca4ff6386b467b0a1c6--valet-php@5.6-5.6.39.mojave.bottle.tar.gz
> ==> Pouring valet-php@5.6-5.6.39.mojave.bottle.tar.gz
> ==> /usr/local/Cellar/valet-php@5.6/5.6.39/bin/pear config-set php_ini /usr/local/etc/valet-php/5.6/php.ini system
> Last 15 lines from /Users/sergey/Library/Logs/Homebrew/valet-php@5.6/post_install.01.pear:
> 2019-04-19 13:11:17 +0200
> 
> /usr/local/Cellar/valet-php@5.6/5.6.39/bin/pear
> config-set
> php_ini
> /usr/local/etc/valet-php/5.6/php.ini
> system
> 
> dyld: Library not loaded: /usr/local/opt/icu4c/lib/libicui18n.63.dylib
>   Referenced from: /usr/local/Cellar/valet-php@5.6/5.6.39/bin/php
>   Reason: image not found
> …
> ```

I've been experiencing the same issue. Currently it's impossible to install valet and get it to work. After hours of crawling all over the internet good old stackoverflow helped me to get it fixed!

**Here's how I did it:**
1. We first need a deep clone of the Homebrew repo. This may take a while: git -C $(brew --repo homebrew/core) fetch --unshallow
2. brew log icu4c to track down a commit that references 63.X; bc0c97952453ff6afc146aa3a706e9902aba4300 does the trick.
3. cd $(brew --repo homebrew/core)
4. git checkout bc0c97952453ff6afc146aa3a706e9902aba4300 -- Formula/icu4c.rb
5. brew uninstall  --ignore-dependencies icu4c
6. brew install icu4c You should now have the correct version of the dependency! Now just to...
7. git reset && git checkout . Cleanup your modified recipe.
8. I had to do a brew switch icu4c 63.1 to make it all work again.

See https://stackoverflow.com/a/54273234 for additional information.
This seems the only way to fix it right now.

**Comment by dostrog** [comment]
Ok. This helped me. Will have to pin this version of icu4c.

Thank you!
